app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
db=SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'z1012194891'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:z1012194891@127.0.0.1:3306/european'
    app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True

    db.init_app(app)


    from .face import face as face_blueprint
    app.register_blueprint(face_blueprint)
#
    return app

app/face/__init__.py
from flask import Blueprint

face = Blueprint('face', __name__)


from . import views

app/face/views.py
import cv2
import face_recognition
import os
from werkzeug.utils import secure_filename
from flask import Flask,render_template,request,g
from . import face
from ..model import player

os.chdir(r'/Users/zengrui/Desktop/媒体大数据/欧洲杯球员识别/app')
number="1"


def dHash(img):
    # 缩放8*8
    img = cv2.resize(img, (9, 8))
    # 转换灰度图
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    hash_str = ''
    # 每行前一个像素大于后一个像素为1，相反为0，生成哈希
    for i in range(8):
        for j in range(8):
            if gray[i, j] > gray[i, j + 1]:
                hash_str = hash_str + '1'
            else:
                hash_str = hash_str + '0'
    return hash_str

def cmpHash(hash1, hash2):
    n = 0
    # hash长度不同则返回-1代表传参出错
    if len(hash1)!=len(hash2):
        return -1
    # 遍历判断
    for i in range(len(hash1)):
        # 不相等则n计数+1，n最终为相似度
        if hash1[i] != hash2[i]:
            n = n + 1
    return n
@face.route('/')
def go():
    return render_template('test.html')

@face.route('/index')
def index():
    return render_template('index.html')

@face.route('/cut',methods=['GET', 'POST'])
def cut():
    #wanted = request.args.get("wanted", type=str)
    #v_path='static/'+wanted+'.mp4'
    if request.method == 'GET':
        return render_template('cut.html')
    else:
        f = request.files['file']
        filename = secure_filename(f.filename)
        f.save(os.path.join('static/video/', filename))
    v_path='static/video/'+filename
    image_save='static/image'
    cap=cv2.VideoCapture(v_path)
    frame_count=cap.get(cv2.CAP_PROP_FRAME_COUNT)
    _,img=cap.read()
    j=0
    for i in range(int(frame_count)-1):
        hash1 = dHash(img)
        _, img2 = cap.read()
        hash2 = dHash(img2)
        n = cmpHash(hash1, hash2)
        #print(n)
        if n>=35:
            j=j+1
            cv2.imwrite('static/image/{}.jpg'.format(j), img)
            img = img2
    cuts = os.listdir(image_save)
    cuts.remove('.DS_Store')
    cuts.sort(key=lambda x:int(x[:-4]))
    p='static/image'
    f_cuts=[p+'/'+cut for cut in cuts]
    # for i in range(len(cuts)):
    #     if cut[i].endswith('jpg'):
    #         cuts[i]=p+'/'+cuts[i]
    return render_template('cut.html',result='Finish!',cuts=f_cuts,path=v_path)

@face.route('/match')
def match():
    try:
        number = request.args.get("wanted", type=str)
        print(number)
        if number == None:
            number = '1'
        path='static/players'
        players=os.listdir(path)
        flag=0
        for i in range(len(players)):
            known_path = path+'/'+players[i]
            unknown_path = "static/image/"+number+".jpg"
            known_image = face_recognition.load_image_file(known_path)
            unknown_image = face_recognition.load_image_file(unknown_path)
            # 获取
            known_encoding = face_recognition.face_encodings(known_image)[0]
            unknown_encoding = face_recognition.face_encodings(unknown_image)[0]
            # 将人脸编码列表与候选编码进行比较，看看它们是否匹配
            # tolerance低于设定的面与面之间的距离视为匹配，越低越严格。默认0.6为典型的最佳性能
            results = face_recognition.compare_faces([known_encoding],
                                                     unknown_encoding,
                                                     tolerance=0.6)
            if results[0]==True:
                flag=1
                name=players[i][:-4]
                print(name)
                res=list(player.query.filter(player.name.like('%'+name+'%')).all())
                rs=[{'name':row.name,'age':row.age,'nationality':row.nationality,'height':row.height} for row in res]
                print(rs)
                break
    except:
        # print(e)
        number = str(int(number) + 1)
        print(number)
        return render_template("match.html" ,outface=unknown_path,result="对不起，未能识别到人脸...",rs=[],number=number)

    else:
        if flag==1:
            number = str(int(number) + 1)
            print(number)
            return render_template('match.html', outface=unknown_path,result='球员匹配成功!',rs=rs[0],number=number)
        else:
            number = str(int(number) + 1)
            print(number)
            return render_template('match.html',outface=unknown_path,result='对不起，未能识别到球员...',rs=[],number=number)

app/templates/cut.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>球员识别系统</title>
</head>
<body>
<h1 style="text-align:center;color:white;font-family:STSong">视频切割</h1>
    <center>
    <form action="/">
        <button type="submit" class ="submit">返回主菜单</button><br>
    </form>
        </center>
<style>
h3 {font-size: 20px;color: white; display : inline}
      .text {
                text-align:center;
<!--                height: 16px;-->
<!--                 width: 120px;-->
                 font-family:STSong;
                }
      .submit {
                height:30px;
                width:200px;
                background-color:white;
                text-align:center;
                }
      body{
    background-image: url(static/2.jpg);
    background-color: rgba(0, 0, 0, 0.1);
    background-size: cover;
    filter:alpha(opacity=60);-moz-opacity:0.6;opacity:0.60;
  }
#gallery {
	margin: 10px auto;
	padding: 40px;
	list-style:none;
	width:530px;
}
#gallery li {
	float:left;
	width:106px;
	height:80px;
	overflow:visible;
}
#gallery li a {
	color:#333;
	text-decoration:none;
	font-size:4px;
	display:block;
	text-align:center;
	background-color:#FFF;
	padding:3px;
	opacity:1;
	box-shadow:0 0 5px 2px #333;
	/* 设计动画过渡效果 */
	-webkit-transition: all 500ms linear;
	-moz-transition: all 500ms linear;
	transition: all 500ms linear;
	/* 自定义变形原点 */
	-webkit-transform-origin:0 0;
	-moz-transform-origin:0 0;
	transform-origin:0 0;
	/* 旋转变形 */
	-webkit-transform:rotate(-15deg);
	-moz-transform:rotate(-15deg);
	transform:rotate(-15deg);
}
#gallery li a img {
	width:100px;
}
#gallery li:nth-child(3n) a {
	-webkit-transform:rotate(20deg);
	-moz-transform:rotate(20deg);
	transform:rotate(20deg);
}
#gallery li:nth-child(4n) a {
	-webkit-transform:rotate(15deg);
	-moz-transform:rotate(15deg);
	transform:rotate(15deg);
}
#gallery li:nth-child(7n) a {
	-webkit-transform:rotate(-10deg);
	-moz-transform:rotate(-10deg);
	transform:rotate(-10deg);
}
#gallery li:nth-child(9n) a {
	-webkit-transform:rotate(-20deg);
	-moz-transform:rotate(-20deg);
	transform:rotate(-20deg);
}
#gallery li a:hover {
	position:relative;
	z-index: 999;
	opacity: 1;
	/* 旋转并放大 */
	-webkit-transform: rotate(0deg) scale(2);
	-moz-transform: rotate(0deg) scale(2);
	transform: rotate(0deg) scale(2);
}
#gallery li a:hover:after {
	content:attr(title);  /* 添加title属性内容 */
}
</style>
</style>
<br>
<center>
    <h3>{{result}}</h3><br>
    <video width="30%" height="30%" style="margin-top:15px;" controls="controls">
    <source src="{{path}}" type="video/mp4" />
    </video>
</center>
<center>
    <form action="/match">
        <input class="submit" type="submit" value="开始识别"></input>
    </form>
</center>
<ul id="gallery">
    {% for cut in cuts %}
    <li><a href="#"><img src="{{cut}}" /></a></li>
    {% endfor %}
</ul>

</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>球员识别系统</title>
</head>
<body>
<h1 style="text-align:center;color:white;font-family:STSong">视频上传、切分</h1>
<style>
h3 {font-size: 20px;color: white; display : inline ;font-family:STSong}
      .text {
                text-align:center;
                height: 16px;
                 width: 120px;
                 font-family:STSong;
                }
      .submit {
                height:30px;
                width:200px;
                background-color:white;
                text-align:center;
                }
      body{
    background-image: url(static/2.jpg);
    background-color: rgba(0, 0, 0, 0.1);
    background-size: cover;
    filter:alpha(opacity=60);-moz-opacity:0.6;opacity:0.60;
  }
</style>
<br>
<center>
    <br><br><br><br>
    <form action="/cut" method="post" enctype="multipart/form-data">
        <h3>选择你的视频路径：</h3>
        <input type="file" name="file" value="" default=""><br><br><br>
{#        <input class='text' type="text" name="wanted" value="" default="">#}
        <input class="submit" type="submit" value="上传并切分视频"><br><br><br><br><br><br><br><br><br><br><br><br>
    </form>
    <form action="/">
        <button type="submit" class ="submit">返回主菜单</button><br>
    </form>
</center>

</body>
</html>

app/templates/match.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>球员识别系统</title>
</head>
<body>
<h1 style="text-align:center;color:white;font-family:STSong">球员识别</h1>
<center>
<form action="/">
        <button type="submit" class ="submit">返回主菜单</button><br>
    </form>
</center>
<style>
h3 {font-size: 20px;color: white; display : inline}
      .text {
                text-align:center;
<!--                height: 16px;-->
<!--                 width: 120px;-->
                 font-family:STSong;
                }
      .submit {
                height:30px;
                width:200px;
                background-color:white;
                text-align:center;
                }
      body{
    background-image: url(static/2.jpg);
    background-color: rgba(0, 0, 0, 0.1);
    background-size: cover;
    filter:alpha(opacity=60);-moz-opacity:0.6;opacity:0.60;
  }
  .alignright {
display : inline ;
float : right ;
}
</style>
<br>

<center>
    <img width="25%" height="25%" src="{{outface}}" /></center>

<center>
    <h3 class="text">{{result}}</h3><br><br>
    <textarea readonly='readonly' class="text">球员:{{rs.name}}</textarea><br>
    <textarea readonly='readonly' class="text">年龄:{{rs.age}}</textarea><br>
    <textarea readonly='readonly' class="text">国家:{{rs.nationality}}</textarea><br>
    <textarea readonly='readonly' class="text">身高(cm):{{rs.height}}</textarea><br>

</center>
<script>
    var wanted={{number}};
<!--    document.getElementById("test").value = wanted;-->
<!--     function testclick(name)-->
<!--    {-->
<!--        window.open("{{ url_for("face.match") }}","_self");-->
<!--    }-->
</script>
    <form action="/match" >
        <center>
<!-- <input type="submit"  class ="submit"  value={{number}} name='wanted'></input>-->
    <button type="submit" class ="submit"  value={{number}} name='wanted'>识别下一张</button><br><br><br><br><br><br><br><br><br><br><br><br><br>
</center>
<!--    <input type="hidden"  id="test" name=wanted>-->

<!--        <button onclick="testclick()" name="wanted">点击我啊</button>-->
    </form>

</body>
</html>

app/templates/test.html

<html>
    <head>
        <title>球员识别系统</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
    </head>
    <style>
    .text{
        color:white;
        text-align: center;
        font-family:STSong ;
    }
    .submit {
                height:100px;
                width:200px;
                background-color:white;
                text-align:center;
                border-radius: 12px;
                }
    body{
    background-image: url(static/2.jpg);
    background-color: rgba(0, 0, 0, 0.1);
    background-size: cover;
    filter:alpha(opacity=60);-moz-opacity:0.6;opacity:0.60;
  }
    </style>
    <body>
        <body>
        <div class="text">
            <h1>球员识别系统</h1>
            <h2>Players'Identification</h2><br><br><br><br><br><br><br><br><br>
            <!-- <h2>Your basic info</h2> -->
             <form action="/index">
<!--                 <strong>Name:</strong>
                <input type="text" name="myname" id="name"/></br>
                </br>
 
                <strong>Passward:</strong>
                <input type="password" name="mypassward" id="passward"/></br>
                </br>
 
                <strong>Age:</strong></br>
                <input type="radio" name="age" value="1" checked="checked"/>Under 13</br>
                <input type="radio" name="age" value="2" />13 or older</br>
                </br>
 
                <strong>Your profile:</strong></br>
                <textarea cols="50" rows="4" name="profile" id="profile"></textarea></br>
                </br>
 
                <strong>Job Role:</strong></br>
                <select>
                    <option value="Front-End Developer" selected="selected" name="job">Front-End Developer</option>
                    <option value="Back-End Developer" name="job">Back-End Developer</option>
                </select></br>
                </br>
 
                <strong>Interests:</strong></br>
                <input type="checkbox" name="development" value="1" checked="checked">Development</br>
                <input type="checkbox" name="design" value="2" >Design</br>
                <input type="checkbox" name="business" value="3" >Business</br>
                </br> -->
 
                <input type="submit"  class ="submit"  value="开始识别之旅" ></input><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
                 <h3>Copyright©顾泽皓 曾锐</h3>
            </form>
        </div>
    </body>
    </body>    
      